### ISSUE TITLE
v5.0 almComplete is not defined (and other callbacks)

### ISSUE THREAD

**Issue by Jebble** [dcooney/wordpress-ajax-load-more#161] opened 2019-05-10 08:24 UTC
Since the update to v5.0 the callbacks no longer work.
I updated my code so all callbacks no longer use `jQuery.fn.alm...` and I updated my script to enqueue after ajax-load-more as well except the callbacks still are not defined.

It works with Legacy support enabled, but the whole point of updating the code is to not be dependent of a legacy fallback.

**Comment by dcooney** [comment] 2019-05-10 12:12
Hi @Jebble If you don't want to use legacy callbacks then you should update your functions to use the new syntax.
https://connekthq.com/plugins/ajax-load-more/docs/callback-functions/

Thanks,

**Comment by Jebble** [comment] 2019-05-10 19:10
As my original message says
"I updated my code so all callbacks no longer use `jQuery.fn.alm...`" 

I have updated my code to use my new syntax AND I have enqueued my Javscript after ajax-load-more but the functions are not defined without legacy mode on

**Comment by dcooney** [comment] 2019-05-10 19:39
Cool.Can you share a link please?

**Comment by Jebble** [comment] 2019-05-10 19:47
I can not currently, the website is on a local development environment in the office and I won't be back until monday.

**Comment by dcooney** [comment] 2019-05-10 19:48
Sure, no worries.
Maybe just create a small reduced test case of the JS you are using when you can.

**Comment by Jebble** [comment] 2019-05-10 20:25
This is the code running

`jQuery(document).on('click', '.news-alm', function(e) {
		e.preventDefault();
		almTriggerClick();
		jQuery(this).addClass('is-loading');
	});

	almComplete = function(alm) {
		jQuery(alm.container).parent().find('.news-alm').blur().removeClass('is-loading');
	};

	almDone = function() {
		jQuery('.news-alm').addClass('done');
		jQuery('.news-alm').blur().find('.text').text('Alle nieuwsberichten zijn geladen');
	};`

**Comment by dcooney** [comment] 2019-05-11 17:00
Hard to say what the issue is without seeing this code in action on a page. 
Is there an error or does not happen?

I haven't had any other issues reported and I have not had issues with callbacks rendered inline on the page or in separate JS files.

**Comment by cngodles** [comment] 2019-05-23 19:50
I had this issue and choosing the Legacy Callback is what fixed it. Any insight into what enabling the Legacy Callback actually does compared to older versions?

**Comment by dcooney** [comment] 2019-05-23 20:05
@cngodles It adds a helper JS file that recreates to old callback & public functions.
https://github.com/dcooney/wordpress-ajax-load-more/blob/master/vendor/js/alm/legacy-callbacks.js

More details: https://connekthq.com/ajax-load-more-5-0/#callback-functions

**Comment by cngodles** [comment] 2019-05-23 20:55
I believe we were creating some filter logic. So for instance, in our code we had:

`jQuery.fn.almFilter(transition, speed, data);`

I see now that you are supposed to use:

`ajaxloadmore.filter(transition, speed, data)`

Problem was that we were using it on more than one site and the plugin upgrade generated a few phone calls. We understand it now, and can at the very least enable Legacy to get it working.

**Comment by dcooney** [comment] 2019-05-28 01:58
closing this. Ill reopen if you can share a link to the issue.

**Closed by dcooney** 2019-05-28 01:58 UTC
