### ISSUE TITLE
SEO extension

### ISSUE THREAD

**Issue by iulianba** [dcooney/wordpress-ajax-load-more#155] opened 2018-11-27 15:36 UTC
Hello,

I have these posts: Post 1, Post 2, Post 3, Post 4

I have a page named Blog in which I use the blog template. Here`s the code from blog.php:

```php 
$args = array(
    'post_type' => 'post',
    'posts_per_page' => 3,
    'post_status' => 'publish',
);
$the_query = new WP_Query($args);
```

This is where I am showing post name and displaying the ajax load more button:

```php
if($the_query->have_posts())
{
    echo '<ul>';

    while($the_query->have_posts()) 
    {
        $the_query->the_post(); 

        echo '<li>' . get_the_title() .'</li>';
    }

    echo do_shortcode( '[ajax_load_more
        post_type="post"
        button_label="Load More"
        posts_per_page="3"
        offset="3"
        pause="true"
        seo="true"
        ]' );
    
    echo '</ul>';
}
```

If I remove seo="true", everything works perfectly. Otherwise, the plugin changes the page url into last displayed post slug: instead of /blog I am getting /post-3. 

This functionality breaks the purpose of the seo extension: ability to push the back button and have ?page=2 in the url.

I tested this in a new WordPress instance with only the plugin and seo extension added.

Please let me know what is wrong and how could I fix this.

Thanks

**Comment by dcooney** [comment] 2018-12-06 15:10
The issue is likely you are running ALM inside an existing loop.

**Comment by dcooney** [comment] 2018-12-06 15:13
Also when using SEO, you should let ALM load all your posts, so remove the initial query.

**Comment by iulianba** [comment] 2018-12-06 15:16
Hello,

This is the only code in the page. There is no other query. I also added before new WP_Query wp reset, nothing changed.

I need to query posts, because this is happening on a custom wp environment and I have custom templates for custom query data.

Is there a fix for this?

Thanks a lot

**Comment by dcooney** [comment] 2018-12-06 15:17
Send me a link please. No idea what you are referring too.

**Comment by iulianba** [comment] 2018-12-06 15:22
Here. The only content of this page is described in my first comment:

http://ajax-wp-test.develop.eiddew.com/ajax-test/

Thanks

**Comment by dcooney** [comment] 2018-12-06 15:23
Can you please try removing the initial query from the page and just leave the ajax load more shortcode?

**Comment by iulianba** [comment] 2018-12-06 15:30
If I am resetting the query before ALM is displayed, the seo module seems to not have any effect. It`s not adding anything on the url.

**Comment by dcooney** [comment] 2018-12-06 15:31
Its working.
![image](https://user-images.githubusercontent.com/428624/49593642-0ca38180-f942-11e8-8be1-d049db1149c0.png)

The issue is you have no posts remaining.

**Comment by iulianba** [comment] 2018-12-06 15:33
There are 9 total posts, 3 displayed when the page is loaded.

Once I click load more, the url should change into http://ajax-wp-test.develop.eiddew.com/ajax-test?page=2

I click the button 3 times until the load more button is disabled. 

The urls stays the same: http://ajax-wp-test.develop.eiddew.com/ajax-test/

Thanks

**Comment by dcooney** [comment] 2018-12-06 15:35
Its working.
http://ajax-wp-test.develop.eiddew.com/ajax-test/page/2/

**Comment by iulianba** [comment] 2018-12-06 15:40
If i access this url directly, it loads the next 6 posts, and it should only load 3 more for page 2. 

Also, if I click again the load more button, the page parameter disappears. The parameters should show up when I click the load more button (it is not showing if you click it after the first page load).

**Comment by dcooney** [comment] 2018-12-06 15:44
It's loading 6 posts for page 2 - this includes the first page of 3 posts.
It appears incorrect because you are loading post 9, 8 and 7 before Ajax Load More and as I said, this will break the functionality of SEO.

Closing this ticket.

**Closed by dcooney** 2018-12-06 15:44 UTC

**Comment by iulianba** [comment] 2018-12-06 15:48
It should not include the first page of 3 posts, because I am using offset 3.

**Comment by dcooney** [comment] 2018-12-06 16:08
Sorry, it doesn't work that way at the moment. I have added this to my enhancement list.
