### ISSUE TITLE
Multiple Custom fields (meta_query) not working

### ISSUE THREAD

**Issue by Mihailo23** [dcooney/wordpress-ajax-load-more#98] opened 2015-11-25 15:16 UTC
I have prices for my product posts and i want to show posts that are in range of two prices, but this is not working

<pre>[ajax_load_more post_type="recipe" meta_key="estimated_cost:estimated_cost" meta_value="100:250" meta_compare=">=:<=" meta_type="NUMERIC:NUMERIC" meta_relation="AND" button_label="Older Posts"]
</pre>
instead of doing the shortcode, it just appears on my page.

Any ideas?

**Comment by dcooney** [comment] 2015-11-25 15:23
Hi!
Do you mean the plugin is just rendering the shortcode and not your content?
If so, it's likely the Ajax Load More js is not be added to your footer.

Can you check the wp_footer() is in footer.php?

**Comment by Mihailo23** [comment] 2015-11-26 09:42
I have other alm shortcodes on the same page (the $_GET parameter is what responsible for showing the one I want), and they all work properly, only this one with 2 meta is just rendering on the page.

Yes, I have wp_footer() in footer.php.

**Comment by dcooney** [comment] 2015-11-26 16:25
Can you share a link? 
Having a hard time understanding what the issue is.

**Comment by Mihailo23** [comment] 2015-12-01 12:00
I found out what the problem was...

the shortcode breaks when it gets to the "<" sign, because it interpret it as an opening html tag.

**Comment by dcooney** [comment] 2015-12-01 14:42
Interesting. I wonder why I cannot reproduce this.
How were you adding the shortcode? 
In the content editor or using do_shortcode() ?

**Comment by Mihailo23** [comment] 2015-12-01 15:38
do_shortcode(), and then when I couldn't solve it, moved it in the content editor and it worked

**Comment by dcooney** [comment] 2015-12-11 02:39
Excellent. Thanks for posting this issue. 
That trac ticket is closed, I wonder if there is another one for do_shortcode().

**Comment by Mihailo23** [comment] 2015-12-11 10:50
If you can, post one yourself, and let me know if you get any feedback :)

**Comment by dcooney** [comment] 2015-12-22 01:15
Hey @Mihailo23,
Just an FYI - In the next version of ALM (2.8.5) you can use 'lessthan' and 'lessthanequalto' as alternatives to '<' and '<=' when building your shortcodes with custom fields.

`[ajax_load_more meta_key="price" meta_value="20" meta_compare="lessthan"]`

It will get converted on the backend.

Closing this...

**Closed by dcooney** 2015-12-22 01:15 UTC
